# Global settings applied to the whole site
[build]
  base = "/"
  publish = "dist"  # Directory to publish (change according to your build directory)
  command = "npm run build"  # Build command
  functions = "./netlify/functions"  # Change "src/functions" to your functions directory path


# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
